# Generated by Django 4.1.5 on 2023-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('preview', models.CharField(max_length=250, verbose_name='Превью')),
                ('news_text', models.TextField(verbose_name='Текст новости')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
